### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by qiwang067** [DeckardAgent/deckard#1]
Hi, Kolby,  we tried to run `python main.py`, and got the following errors.
```bash
Traceback (most recent call last):
  File "/home/qwang/deckard/main.py", line 149, in <module>
    next_task = explore_techtree(model.env, model.policy, allow_sample_untrained=False, max_explore_steps=args.explore_steps)
  File "/home/qwang/deckard/techtree.py", line 25, in explore_techtree
    last_obs = env.reset()
  File "/home/qwang/.conda/envs/mineclip/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 135, in reset
    obs = [remote.recv() for remote in self.remotes]
  File "/home/qwang/.conda/envs/mineclip/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 135, in <listcomp>
    obs = [remote.recv() for remote in self.remotes]
  File "/home/qwang/.conda/envs/mineclip/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/qwang/.conda/envs/mineclip/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/qwang/.conda/envs/mineclip/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by kolbytn** [comment]
This error is raised when any of the remote environments raises an exception, so it is very uninformative. Have you modified the original environments or agent at all? You can try switching from subprocesses to "DummyVecEnv"s to get a more informative trace.

**Comment by qiwang067** [comment]
Thank you for your response. I will contact you if there are any further questions.

> This error is raised when any of the remote environments raises an exception, so it is very uninformative. Have you modified the original environments or agent at all? You can try switching from subprocesses to "DummyVecEnv"s to get a more informative trace.
